name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build APK
        uses: amirisback/automated-build-android-app-with-github-action@master
        continue-on-error: true
        with:
          app_name: "RiderTracker"
          package_name: "com.madcarbone.rider"

      - name: Search and Collect
        run: |
          mkdir -p final_output
          # Cerchiamo qualsiasi file APK o HTML e mettiamolo nella cartella di scaricamento
          find . -name "*.apk" -exec cp {} final_output/ \;
          cp index.html final_output/ || true

      - name: Upload Everything
        uses: actions/upload-artifact@v4
        with:
          name: Rider-Tracker-Final-Package
          path: final_output/
